service: my-store-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin
  - serverless-s3-cleaner

custom:
  client:
    bucketName: my-ecomm-sls
    distributionFolder: dist
  s3BucketName: ${self:custom.client.bucketName}
  s3LocalPath: ${self:custom.client.distributionFolder}/
  serverless-s3-cleaner:
    buckets:
      - ${self:custom.client.bucketName}

resources:
  - ${file(./sls/s3.yml)}
  - ${file(./sls/cloudfront.yml)}
